# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20170331_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='puajs',
            field=models.ManyToManyField(blank=True, related_name='mis_puajs', to=settings.AUTH_USER_MODEL),
        ),
    ]
